/* ============================================================
   MVR DELUXE BOYS HOSTEL — data layer
   --------------------------------------------------------------
   DEMO DATA STORE. Everything here lives in the browser's
   localStorage so the site is fully functional the moment you
   open it — no server needed to try it out. Open the Student
   Portal and the Admin Portal in two tabs of the SAME browser
   and you'll see presence / reports flow between them live,
   because they share one localStorage.

   IMPORTANT — before this goes live with real student data:
   localStorage lives only in one browser on one device, and the
   demo passwords below are stored in plain text in this file,
   visible to anyone who views the page source. That's fine for
   a demo, not for a real hostel roll with real students. See
   README.md for how to swap this file for a real backend
   (Supabase, the same approach used on srimedhaedu.in) without
   touching any other page.

   AADHAAR NUMBERS — extra caution:
   Each student record below includes a demo Aadhaar number.
   This is a sensitive Indian government ID number. This site
   never displays the full number anywhere in the UI — every
   screen and CSV export only ever shows maskAadhaar()'s output
   (last 4 digits). Do NOT add code that prints the raw
   `aadhaar` field to the page. Before using this with real
   students' real Aadhaar numbers, this needs a real backend
   with encryption at rest and proper access control — a static
   client-side site with plaintext localStorage is not a safe
   place to hold real government ID numbers, full stop.
   ============================================================ */

const DB_KEYS = {
  students: 'mvr_students',
  presence: 'mvr_presence',
  reports:  'mvr_reports',
  notices:  'mvr_notices',
  session:  'mvr_session'
};

/* ============================================================
   REAL STUDENT ROSTER — transcribed from the physical room
   register (Aug 2026), room by room. Notes on this data:

   - `username` is the student's 10-digit mobile number where the
     register recorded one. About 66 of the 84 students had no
     mobile number written down, so those got an auto-generated
     username (their name, lowercased). `loginReady: false` flags
     exactly those — the admin should add each one's mobile number
     via the Edit form (which also lets you set/replace their
     username and password) before they can sign in.
   - Every student's password defaults to 'hostel@123' — the same
     demo default as before. Change this per-student from the
     admin Edit form once real logins are handed out.
   - `course`, `block`, `sharing`, `guardian`, `aadhaar`,
     `bloodGroup` and `rollNumber` were not in the register, so
     they're blank here — fill them in via the admin Edit form as
     you collect them. `room` holds the literal room number from
     the register (e.g. "4/B", "12/A", "16").
   - `registerNote` carries anything that was unclear or worth
     double-checking on the original photographed page (unclear
     handwriting, a rotated photo, a possible duplicate entry,
     etc). Check any student where this isn't blank.
   ============================================================ */
const SEED_STUDENTS = [
  {
    id: "MVR26-001",
    username: "panvesh",
    password: "hostel@123",
    name: "P. Anvesh",
    course: "",
    block: "",
    room: "1/A",
    sharing: "",
    joined: "2025-09-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-002",
    username: "bnitish",
    password: "hostel@123",
    name: "B. Nitish",
    course: "",
    block: "",
    room: "1/A",
    sharing: "",
    joined: "2025-12-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "Marked 'vacated' in register",
  },
  {
    id: "MVR26-003",
    username: "manilkumar",
    password: "hostel@123",
    name: "M. Anil Kumar",
    course: "",
    block: "",
    room: "1/A",
    sharing: "",
    joined: "2026-05-28",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-004",
    username: "vmadhu",
    password: "hostel@123",
    name: "V. Madhu",
    course: "",
    block: "",
    room: "1/B",
    sharing: "",
    joined: "2025-08-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "Cash column entry unclear ('B-300'), please verify",
  },
  {
    id: "MVR26-005",
    username: "pakash",
    password: "hostel@123",
    name: "P. Akash",
    course: "",
    block: "",
    room: "1/B",
    sharing: "",
    joined: "2025-08-18",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-006",
    username: "gveerashankar",
    password: "hostel@123",
    name: "G. Veera Shankar",
    course: "",
    block: "",
    room: "1/B",
    sharing: "",
    joined: "2024-08-22",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-007",
    username: "bharshith",
    password: "hostel@123",
    name: "B. Harshith",
    course: "",
    block: "",
    room: "1/B",
    sharing: "",
    joined: "2026-08-21",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-008",
    username: "gakshaypaul",
    password: "hostel@123",
    name: "G. Akshaypaul",
    course: "",
    block: "",
    room: "2",
    sharing: "",
    joined: "2025-09-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-009",
    username: "brajesh",
    password: "hostel@123",
    name: "B. Rajesh",
    course: "",
    block: "",
    room: "2",
    sharing: "",
    joined: "2025-09-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-010",
    username: "gsailivek",
    password: "hostel@123",
    name: "G. Sailivek",
    course: "",
    block: "",
    room: "2",
    sharing: "",
    joined: "2025-09-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-011",
    username: "vshivamani",
    password: "hostel@123",
    name: "V. Shivamani",
    course: "",
    block: "",
    room: "2",
    sharing: "",
    joined: "2025-09-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-012",
    username: "gprabath",
    password: "hostel@123",
    name: "G. Prabath",
    course: "",
    block: "",
    room: "2",
    sharing: "",
    joined: "2025-09-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-013",
    username: "vpramkumar",
    password: "hostel@123",
    name: "V. Pramkumar",
    course: "",
    block: "",
    room: "2",
    sharing: "",
    joined: "2026-08-01",
    guardian: "",
    contact: "9100365",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "Mobile number partly unclear, please verify",
  },
  {
    id: "MVR26-014",
    username: "gabhishek",
    password: "hostel@123",
    name: "G. Abhishek",
    course: "",
    block: "",
    room: "3",
    sharing: "",
    joined: "2025-08-03",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-015",
    username: "gvikram",
    password: "hostel@123",
    name: "G. Vikram",
    course: "",
    block: "",
    room: "3",
    sharing: "",
    joined: "2025-09-05",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-016",
    username: "janil",
    password: "hostel@123",
    name: "J. Anil",
    course: "",
    block: "",
    room: "3",
    sharing: "",
    joined: "2026-08-09",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-017",
    username: "gnarshima",
    password: "hostel@123",
    name: "G. Narshima",
    course: "",
    block: "",
    room: "3",
    sharing: "",
    joined: "2025-11-20",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-018",
    username: "ggopikrishna",
    password: "hostel@123",
    name: "G. Gopi Krishna",
    course: "",
    block: "",
    room: "3",
    sharing: "",
    joined: "2025-07-27",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "Join year unclear, could be 27-7-25 or 27-7-28",
  },
  {
    id: "MVR26-019",
    username: "uanand",
    password: "hostel@123",
    name: "U. Anand",
    course: "",
    block: "",
    room: "3",
    sharing: "",
    joined: "2025-11-20",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-020",
    username: "pajay",
    password: "hostel@123",
    name: "P. Ajay",
    course: "",
    block: "",
    room: "3",
    sharing: "",
    joined: "2025-06-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "Page image was rotated, please double-check all rows in this block",
  },
  {
    id: "MVR26-021",
    username: "bsaiprasad",
    password: "hostel@123",
    name: "B. Sai Prasad",
    course: "",
    block: "",
    room: "3",
    sharing: "",
    joined: "2025-06-30",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-022",
    username: "vajay",
    password: "hostel@123",
    name: "V. Ajay",
    course: "",
    block: "",
    room: "3",
    sharing: "",
    joined: "2025-09-18",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-023",
    username: "achandu",
    password: "hostel@123",
    name: "A. Chandu",
    course: "",
    block: "",
    room: "3",
    sharing: "",
    joined: "2026-07-18",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-024",
    username: "nsasikanth",
    password: "hostel@123",
    name: "N. Sasikanth",
    course: "",
    block: "",
    room: "3",
    sharing: "",
    joined: "2026-08-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-025",
    username: "sanilkumar",
    password: "hostel@123",
    name: "S. Anil Kumar",
    course: "",
    block: "",
    room: "3",
    sharing: "",
    joined: "2026-08-05",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-026",
    username: "sumanth",
    password: "hostel@123",
    name: "Sumanth",
    course: "",
    block: "",
    room: "3",
    sharing: "",
    joined: "2026-08-05",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-027",
    username: "bganesh",
    password: "hostel@123",
    name: "B. Ganesh",
    course: "",
    block: "",
    room: "8/A",
    sharing: "",
    joined: "2024-08-12",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "Page image was rotated, please double-check",
  },
  {
    id: "MVR26-028",
    username: "jloketh",
    password: "hostel@123",
    name: "J. Loketh",
    course: "",
    block: "",
    room: "8/A",
    sharing: "",
    joined: "2024-08-12",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-029",
    username: "gvamshi",
    password: "hostel@123",
    name: "G. Vamshi",
    course: "",
    block: "",
    room: "8/A",
    sharing: "",
    joined: "2024-08-12",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-030",
    username: "gdurgaraju",
    password: "hostel@123",
    name: "G. Durgaraju",
    course: "",
    block: "",
    room: "8/A",
    sharing: "",
    joined: "2024-08-22",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-031",
    username: "vchaitanya",
    password: "hostel@123",
    name: "V. Chaitanya",
    course: "",
    block: "",
    room: "9",
    sharing: "",
    joined: "2025-11-19",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "Page image was rotated, please double-check",
  },
  {
    id: "MVR26-032",
    username: "kharshith",
    password: "hostel@123",
    name: "K. Harshith",
    course: "",
    block: "",
    room: "9",
    sharing: "",
    joined: "2025-08-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-033",
    username: "chabhilesh",
    password: "hostel@123",
    name: "Ch. Abhilesh",
    course: "",
    block: "",
    room: "9",
    sharing: "",
    joined: "2025-11-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-034",
    username: "chravitej",
    password: "hostel@123",
    name: "Ch. Ravitej",
    course: "",
    block: "",
    room: "9",
    sharing: "",
    joined: "",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "Row largely unclear in photo — confirm this student is current",
  },
  {
    id: "MVR26-035",
    username: "7601010514",
    password: "hostel@123",
    name: "B. Manidu",
    course: "",
    block: "",
    room: "9",
    sharing: "",
    joined: "2026-08-15",
    guardian: "",
    contact: "7601010514",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: true,
    registerNote: "",
  },
  {
    id: "MVR26-036",
    username: "7992029436",
    password: "hostel@123",
    name: "Gh. Manikanta",
    course: "",
    block: "",
    room: "9",
    sharing: "",
    joined: "2026-08-18",
    guardian: "",
    contact: "7992029436",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: true,
    registerNote: "",
  },
  {
    id: "MVR26-037",
    username: "dbhanu",
    password: "hostel@123",
    name: "D. Bhanu",
    course: "",
    block: "",
    room: "4/A",
    sharing: "",
    joined: "2025-12-18",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-038",
    username: "vravichandra",
    password: "hostel@123",
    name: "V. Ravichandra",
    course: "",
    block: "",
    room: "4/A",
    sharing: "",
    joined: "2025-10-02",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-039",
    username: "kmeghnath",
    password: "hostel@123",
    name: "K. Meghnath",
    course: "",
    block: "",
    room: "4/A",
    sharing: "",
    joined: "2025-07-29",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-040",
    username: "psidharath",
    password: "hostel@123",
    name: "P. Sidharath",
    course: "",
    block: "",
    room: "4/B",
    sharing: "",
    joined: "2025-10-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-041",
    username: "pvishwanth",
    password: "hostel@123",
    name: "P. Vishwanth",
    course: "",
    block: "",
    room: "4/B",
    sharing: "",
    joined: "2025-10-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-042",
    username: "mnikhil",
    password: "hostel@123",
    name: "M. Nikhil",
    course: "",
    block: "",
    room: "4/B",
    sharing: "",
    joined: "2025-07-25",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-043",
    username: "ksumithkumar",
    password: "hostel@123",
    name: "K. Sumith Kumar",
    course: "",
    block: "",
    room: "5",
    sharing: "",
    joined: "2025-08-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-044",
    username: "bsaikrishna",
    password: "hostel@123",
    name: "B. Saikrishna",
    course: "",
    block: "",
    room: "5",
    sharing: "",
    joined: "2025-07-06",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "Online amount partly unclear, appears 5000",
  },
  {
    id: "MVR26-045",
    username: "agoutham",
    password: "hostel@123",
    name: "A. Goutham",
    course: "",
    block: "",
    room: "5",
    sharing: "",
    joined: "2025-07-11",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-046",
    username: "amithkumar",
    password: "hostel@123",
    name: "Amith Kumar",
    course: "",
    block: "",
    room: "6",
    sharing: "",
    joined: "2025-09-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-047",
    username: "akinandhan",
    password: "hostel@123",
    name: "Akinandhan",
    course: "",
    block: "",
    room: "6",
    sharing: "",
    joined: "2025-10-13",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-048",
    username: "7981685864",
    password: "hostel@123",
    name: "K. Ranjith",
    course: "",
    block: "",
    room: "6",
    sharing: "",
    joined: "2026-08-02",
    guardian: "",
    contact: "7981685864",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: true,
    registerNote: "",
  },
  {
    id: "MVR26-049",
    username: "pshashank",
    password: "hostel@123",
    name: "P. Shashank",
    course: "",
    block: "",
    room: "10",
    sharing: "",
    joined: "2025-08-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-050",
    username: "npranayjood",
    password: "hostel@123",
    name: "N. Pranay Jood",
    course: "",
    block: "",
    room: "10",
    sharing: "",
    joined: "2025-07-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "Surname 'Jood' unclear",
  },
  {
    id: "MVR26-051",
    username: "mpradeep",
    password: "hostel@123",
    name: "M. Pradeep",
    course: "",
    block: "",
    room: "10",
    sharing: "",
    joined: "2025-07-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-052",
    username: "npoorthu",
    password: "hostel@123",
    name: "N. Poorthu",
    course: "",
    block: "",
    room: "10",
    sharing: "",
    joined: "2025-07-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "Name unclear",
  },
  {
    id: "MVR26-053",
    username: "tvishwarth",
    password: "hostel@123",
    name: "T. Vishwarth",
    course: "",
    block: "",
    room: "10",
    sharing: "",
    joined: "2025-01-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "Join date unclear",
  },
  {
    id: "MVR26-054",
    username: "ppraneeth",
    password: "hostel@123",
    name: "P. Praneeth",
    course: "",
    block: "",
    room: "10",
    sharing: "",
    joined: "2025-07-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-055",
    username: "pmukesh",
    password: "hostel@123",
    name: "P. Mukesh",
    course: "",
    block: "",
    room: "10",
    sharing: "",
    joined: "2026-05-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-056",
    username: "9553068853",
    password: "hostel@123",
    name: "G. Jaswanth",
    course: "",
    block: "",
    room: "11",
    sharing: "",
    joined: "2026-07-21",
    guardian: "",
    contact: "9553068853",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: true,
    registerNote: "",
  },
  {
    id: "MVR26-057",
    username: "6305886562",
    password: "hostel@123",
    name: "B. Venkatesh",
    course: "",
    block: "",
    room: "11",
    sharing: "",
    joined: "2026-07-21",
    guardian: "",
    contact: "6305886562",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: true,
    registerNote: "",
  },
  {
    id: "MVR26-058",
    username: "8340876059",
    password: "hostel@123",
    name: "B. Abhinav",
    course: "",
    block: "",
    room: "11",
    sharing: "",
    joined: "2026-07-21",
    guardian: "",
    contact: "8340876059",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: true,
    registerNote: "",
  },
  {
    id: "MVR26-059",
    username: "9014480827",
    password: "hostel@123",
    name: "G. Sivaraj",
    course: "",
    block: "",
    room: "11",
    sharing: "",
    joined: "2026-07-21",
    guardian: "",
    contact: "9014480827",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: true,
    registerNote: "",
  },
  {
    id: "MVR26-060",
    username: "9182136057",
    password: "hostel@123",
    name: "G. Vishal",
    course: "",
    block: "",
    room: "11",
    sharing: "",
    joined: "2026-07-21",
    guardian: "",
    contact: "9182136057",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: true,
    registerNote: "",
  },
  {
    id: "MVR26-061",
    username: "charun",
    password: "hostel@123",
    name: "Ch. Arun",
    course: "",
    block: "",
    room: "12/A",
    sharing: "",
    joined: "2025-03-07",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-062",
    username: "mnithin",
    password: "hostel@123",
    name: "M. Nithin",
    course: "",
    block: "",
    room: "12/A",
    sharing: "",
    joined: "2025-08-04",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-063",
    username: "kshiva",
    password: "hostel@123",
    name: "K. Shiva",
    course: "",
    block: "",
    room: "12/A",
    sharing: "",
    joined: "2025-07-27",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-064",
    username: "mvarun",
    password: "hostel@123",
    name: "M. Varun",
    course: "",
    block: "",
    room: "12/A",
    sharing: "",
    joined: "2025-07-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-065",
    username: "8309888205",
    password: "hostel@123",
    name: "Ch. Varun Tej",
    course: "",
    block: "",
    room: "12/B",
    sharing: "",
    joined: "2026-07-13",
    guardian: "",
    contact: "8309888205",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: true,
    registerNote: "",
  },
  {
    id: "MVR26-066",
    username: "9346143990",
    password: "hostel@123",
    name: "A. Aswith",
    course: "",
    block: "",
    room: "12/B",
    sharing: "",
    joined: "2026-07-13",
    guardian: "",
    contact: "9346143990",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: true,
    registerNote: "",
  },
  {
    id: "MVR26-067",
    username: "9121292240",
    password: "hostel@123",
    name: "G. Manideep",
    course: "",
    block: "",
    room: "12/B",
    sharing: "",
    joined: "2026-07-12",
    guardian: "",
    contact: "9121292240",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: true,
    registerNote: "",
  },
  {
    id: "MVR26-068",
    username: "6302391805",
    password: "hostel@123",
    name: "A. Rakesh",
    course: "",
    block: "",
    room: "12/B",
    sharing: "",
    joined: "2026-08-01",
    guardian: "",
    contact: "6302391805",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: true,
    registerNote: "",
  },
  {
    id: "MVR26-069",
    username: "mrohit",
    password: "hostel@123",
    name: "M. Rohit",
    course: "",
    block: "",
    room: "13",
    sharing: "",
    joined: "2025-08-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-070",
    username: "ssanjay",
    password: "hostel@123",
    name: "S. Sanjay",
    course: "",
    block: "",
    room: "13",
    sharing: "",
    joined: "",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "No data recorded in register — confirm this student is current",
  },
  {
    id: "MVR26-071",
    username: "mnaveen",
    password: "hostel@123",
    name: "M. Naveen",
    course: "",
    block: "",
    room: "13",
    sharing: "",
    joined: "2025-08-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-072",
    username: "shaikafraz",
    password: "hostel@123",
    name: "Shaik Afraz",
    course: "",
    block: "",
    room: "13",
    sharing: "",
    joined: "2025-09-20",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "Online amount cut off in photo",
  },
  {
    id: "MVR26-073",
    username: "bveerith",
    password: "hostel@123",
    name: "B. Veerith",
    course: "",
    block: "",
    room: "13",
    sharing: "",
    joined: "2025-06-30",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-074",
    username: "7989450942",
    password: "hostel@123",
    name: "Touheed Pasha",
    course: "",
    block: "",
    room: "13",
    sharing: "",
    joined: "2026-08-11",
    guardian: "",
    contact: "7989450942",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: true,
    registerNote: "Amount partly cut off in photo",
  },
  {
    id: "MVR26-075",
    username: "nkarthik",
    password: "hostel@123",
    name: "N. Karthik",
    course: "",
    block: "",
    room: "14",
    sharing: "",
    joined: "2025-08-06",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-076",
    username: "tnarender",
    password: "hostel@123",
    name: "T. Narender",
    course: "",
    block: "",
    room: "14",
    sharing: "",
    joined: "2025-02-16",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "",
  },
  {
    id: "MVR26-077",
    username: "mvinyl",
    password: "hostel@123",
    name: "M. Vinyl",
    course: "",
    block: "",
    room: "14",
    sharing: "",
    joined: "2025-09-20",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "Name unclear",
  },
  {
    id: "MVR26-078",
    username: "9381927464",
    password: "hostel@123",
    name: "T. Ranjith",
    course: "",
    block: "",
    room: "14",
    sharing: "",
    joined: "2026-08-02",
    guardian: "",
    contact: "9381927464",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: true,
    registerNote: "",
  },
  {
    id: "MVR26-079",
    username: "msrinivas",
    password: "hostel@123",
    name: "M. Srinivas",
    course: "",
    block: "",
    room: "14",
    sharing: "",
    joined: "2026-08-11",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "Name unclear",
  },
  {
    id: "MVR26-080",
    username: "6304837840",
    password: "hostel@123",
    name: "K. Ashok",
    course: "",
    block: "",
    room: "16",
    sharing: "",
    joined: "2026-08-01",
    guardian: "",
    contact: "6304837840",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: true,
    registerNote: "",
  },
  {
    id: "MVR26-081",
    username: "6300283787",
    password: "hostel@123",
    name: "K. Charan",
    course: "",
    block: "",
    room: "16",
    sharing: "",
    joined: "2026-08-10",
    guardian: "",
    contact: "6300283787",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: true,
    registerNote: "",
  },
  {
    id: "MVR26-082",
    username: "9014780747",
    password: "hostel@123",
    name: "M. Siddhu",
    course: "",
    block: "",
    room: "16",
    sharing: "",
    joined: "2026-08-06",
    guardian: "",
    contact: "9014780747",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: true,
    registerNote: "",
  },
  {
    id: "MVR26-083",
    username: "kcharan2",
    password: "hostel@123",
    name: "K. Charan (2)",
    course: "",
    block: "",
    room: "16",
    sharing: "",
    joined: "2026-08-01",
    guardian: "",
    contact: "",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: false,
    registerNote: "Possible duplicate/second entry for a K. Charan — please confirm with the register",
  },
  {
    id: "MVR26-084",
    username: "8978026939",
    password: "hostel@123",
    name: "P. Sheshadri",
    course: "",
    block: "",
    room: "16",
    sharing: "",
    joined: "2026-08-15",
    guardian: "",
    contact: "8978026939",
    aadhaar: "",
    bloodGroup: "",
    rollNumber: "",
    loginReady: true,
    registerNote: "",
  },
];

const SEED_NOTICES = [
  { date: '2026-08-20', title: 'Mess menu updated for the week', body: 'Friday dinner changed to paneer butter masala. Full menu on the notice board outside the mess hall.' },
  { date: '2026-08-18', title: 'Water tank cleaning — B Block', body: 'B Block water supply will pause 10 AM–1 PM on Aug 24 for scheduled tank cleaning.' },
  { date: '2026-08-12', title: 'Mark yourself before you leave', body: 'Please use the "Going out" button whenever you will miss a mess meal — it helps us cook the right quantity.' }
];

function seedIfEmpty(key, seed){
  if(!localStorage.getItem(key)){
    localStorage.setItem(key, JSON.stringify(seed));
  }
}
// Bumping this forces every browser to pick up the real roster below even
// if it already had the old 3-student demo data saved. Any student added,
// edited or removed later through the admin portal survives this — the
// version check only fires once per browser, the first time it sees this
// new number.
const DB_VERSION = 2;
function initDB(){
  const seenVersion = Number(localStorage.getItem('mvr_db_version') || '0');
  if(seenVersion < DB_VERSION){
    localStorage.setItem(DB_KEYS.students, JSON.stringify(SEED_STUDENTS));
    localStorage.setItem('mvr_db_version', String(DB_VERSION));
  }
  seedIfEmpty(DB_KEYS.students, SEED_STUDENTS);
  seedIfEmpty(DB_KEYS.presence, []);
  seedIfEmpty(DB_KEYS.reports, []);
  seedIfEmpty(DB_KEYS.notices, SEED_NOTICES);
}
initDB();

function readStore(key){ try{ return JSON.parse(localStorage.getItem(key)) || []; }catch(e){ return []; } }
function writeStore(key, val){ localStorage.setItem(key, JSON.stringify(val)); }

/* ---------- students ---------- */
function getStudents(){ return readStore(DB_KEYS.students); }
function findStudentByLogin(username, password){
  return getStudents().find(s => s.username.toLowerCase() === username.trim().toLowerCase() && s.password === password);
}
function getStudentById(id){ return getStudents().find(s => s.id === id); }

/* ---------- admin: add / edit / remove students ---------- */
function nextStudentId(){
  const nums = getStudents()
    .map(s => Number(String(s.id).split('-').pop()))
    .filter(n => !isNaN(n));
  const next = (nums.length ? Math.max(...nums) : 0) + 1;
  return 'MVR26-' + String(next).padStart(3, '0');
}
// Adds a new student. `data` should have at least name, room and username;
// anything left out defaults sensibly. Returns the new student record.
function addStudent(data){
  const all = getStudents();
  const rec = {
    id: nextStudentId(),
    username: '', password: 'hostel@123', name: '', course: '', block: '',
    room: '', sharing: '', joined: new Date().toISOString().slice(0,10),
    guardian: '', contact: '', aadhaar: '', bloodGroup: '', rollNumber: '',
    loginReady: false, registerNote: '',
    ...data
  };
  rec.loginReady = !!(rec.username && rec.username.trim());
  all.push(rec);
  writeStore(DB_KEYS.students, all);
  return rec;
}
// Updates an existing student by id. Only the fields present in `changes`
// are touched — everything else on the record is left as-is.
function updateStudent(id, changes){
  const all = getStudents();
  const rec = all.find(s => s.id === id);
  if(!rec) return null;
  Object.assign(rec, changes);
  rec.loginReady = !!(rec.username && rec.username.trim());
  writeStore(DB_KEYS.students, all);
  return rec;
}
// Removes a student (e.g. they've left the hostel). Also clears any of
// their presence records so they don't linger in the headcount.
function deleteStudent(id){
  writeStore(DB_KEYS.students, getStudents().filter(s => s.id !== id));
  writeStore(DB_KEYS.presence, readStore(DB_KEYS.presence).filter(p => p.studentId !== id));
}

/* Never render the raw aadhaar field — always go through this. */
function maskAadhaar(number){
  if(!number) return '—';
  const digits = String(number).replace(/\s+/g,'');
  return 'XXXX XXXX ' + digits.slice(-4);
}

/* ---------- presence (headcount for the mess, not a permission system) ---------- */
// A student with no entry here is simply "Present". An entry means "Away"
// until the stored return date, at which point they press "I'm back" and
// the entry is removed.
function getAwayRecord(studentId){
  return readStore(DB_KEYS.presence).find(p => p.studentId === studentId) || null;
}
function isAway(studentId){ return !!getAwayRecord(studentId); }
function markAway(studentId, daysAway, returnDate){
  const all = readStore(DB_KEYS.presence).filter(p => p.studentId !== studentId);
  all.push({ studentId, daysAway: Number(daysAway), returnDate, since: new Date().toISOString() });
  writeStore(DB_KEYS.presence, all);
}
function markPresent(studentId){
  const all = readStore(DB_KEYS.presence).filter(p => p.studentId !== studentId);
  writeStore(DB_KEYS.presence, all);
}
function getHeadcount(){
  const students = getStudents();
  const away = readStore(DB_KEYS.presence);
  const awayIds = new Set(away.map(a => a.studentId));
  const awayList = away.map(a => ({ ...a, student: getStudentById(a.studentId) })).filter(a => a.student);
  return {
    total: students.length,
    present: students.length - awayIds.size,
    away: awayIds.size,
    awayList
  };
}

/* ---------- reports ---------- */
function getReports(){ return readStore(DB_KEYS.reports).sort((a,b)=> b.createdAt.localeCompare(a.createdAt)); }
function getReportsFor(studentId){ return getReports().filter(r => r.studentId === studentId); }
function addReport(entry){
  const all = readStore(DB_KEYS.reports);
  const rec = {
    id: 'RPT-' + Date.now().toString(36).toUpperCase(),
    status: 'Submitted',
    createdAt: new Date().toISOString(),
    remark: '',
    ...entry
  };
  all.push(rec);
  writeStore(DB_KEYS.reports, all);
  return rec;
}
function updateReportStatus(id, status, remark){
  const all = readStore(DB_KEYS.reports);
  const rec = all.find(r => r.id === id);
  if(rec){ rec.status = status; rec.remark = remark || rec.remark; }
  writeStore(DB_KEYS.reports, all);
}

/* ---------- notices ---------- */
function getNotices(){ return readStore(DB_KEYS.notices).sort((a,b)=> b.date.localeCompare(a.date)); }
function addNotice(entry){
  const all = readStore(DB_KEYS.notices);
  all.push({ date: new Date().toISOString().slice(0,10), ...entry });
  writeStore(DB_KEYS.notices, all);
}

/* ---------- session ---------- */
function setSession(role, id){ sessionStorage.setItem(DB_KEYS.session, JSON.stringify({ role, id })); }
function getSession(){ try{ return JSON.parse(sessionStorage.getItem(DB_KEYS.session)); }catch(e){ return null; } }
function clearSession(){ sessionStorage.removeItem(DB_KEYS.session); }

/* ---------- csv export ---------- */
function toCSV(rows, columns){
  const head = columns.map(c=>c.label).join(',');
  const body = rows.map(r => columns.map(c => {
    let v = c.get(r); v = (v===undefined||v===null) ? '' : String(v).replace(/"/g,'""');
    return /[,"\n]/.test(v) ? `"${v}"` : v;
  }).join(',')).join('\n');
  return head + '\n' + body;
}
function downloadCSV(filename, csv){
  const blob = new Blob([csv], { type:'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}
